version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - run:
          name: Install Docker client
          command: apk --no-cache add docker
      - run:
          name: 
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build --ssh default -t r6by/docker-experimental-ssh-circleci:$TAG .
