version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10
    environment:
      DOCKER_BUILDKIT: 1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 68:bb:c2:80:0c:d5:66:63:bd:e5:8a:c4:cb:20:87:fd
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.09.3
      - run:
          name: Install Docker client
          command: apk --no-cache add docker
      - run:
          name: 
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build --ssh github-test-private-repo=/root/.ssh/id_rsa_68bbc2800cd56663bde58ac4cb2087fd -t r6by/docker-experimental-ssh-circleci:$TAG .
