version: 2
jobs:
  build-push:
    docker:
      - image: alpine:3.10
    environment:
      BASH_ENV: /etc/profile
      DOCKER_BUILDKIT: 1
      PRIVATE_KEY: id_rsa_68bbc2800cd56663bde58ac4cb2087fd
    shell: /bin/sh -leo pipefail
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 68:bb:c2:80:0c:d5:66:63:bd:e5:8a:c4:cb:20:87:fd
      - setup_remote_docker:
          # docker_layer_caching: true
          version: 18.09.3
      - run:
          name: Install Docker client
          command: apk --no-cache --no-progress add docker openssh-client
      - run:
          name: Define image tag
          command: |
            echo 'export TAG=0.1.$CIRCLE_BUILD_NUM' >> $BASH_ENV
      - run:
          name: Build Docker image
          command: |
            docker build --progress=plain --ssh default=/root/.ssh/$PRIVATE_KEY -t r6by/docker-experimental-ssh-circleci:$TAG -t r6by/docker-experimental-ssh-circleci:latest .
      - run:
          name: Docker login
          command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Push Docker image
          command: |
            docker push r6by/docker-experimental-ssh-circleci:$TAG
            docker push r6by/docker-experimental-ssh-circleci:latest
workflows:
  version: 2
  build-push:
    jobs:
      - build-push:
          filters:
            branches:
              only:
                - master
                - default-ssh-auth-sock
